/**
 * Icons used by the application, re-exported so that ui/ stays the only place importing @lucide/vue.
 * Pass one to <AppIcon :icon="..."/>.
 */
import { createLucideIcon, type LucideIconNode } from '@lucide/vue';

export {
  AlertTriangle,
  ArrowDownWideNarrow,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpNarrowWide,
  Ban,
  BarChart3,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  Clock,
  Columns2,
  Copy,
  Dices,
  Download,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileJson,
  FileSearch,
  FileText,
  Film,
  Fingerprint,
  Folder,
  FolderInput,
  FolderOpen,
  FolderPlus,
  FolderUp,
  HardDrive,
  Hash,
  Heart,
  History,
  Image,
  ImageOff,
  Info,
  KeyRound,
  Keyboard,
  Layers,
  LayoutGrid,
  ListFilter,
  Loader2,
  Maximize2,
  Minus,
  Moon,
  MoreVertical,
  Music,
  Palette,
  Pause,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  RotateCcw,
  Scan,
  ScanSearch,
  Search,
  Settings,
  Shuffle,
  Sparkles,
  Square,
  SquareCheck,
  Sun,
  SunMoon,
  Tag,
  Tags,
  Trash2,
  Upload,
  Waves,
  X,
  ZoomIn,
  ZoomOut,
} from '@lucide/vue';

// The app's own mark: a five-petal cherry blossom, notched petals and no stem or leaves, drawn in
// Lucide's grid and stroke so it sits with the other icons. The favicon is the same blossom.
const PETAL = 'M12 9.8C9.6 8.2 9.1 4.6 10.6 2.9L12 4l1.4-1.1c1.5 1.7 1 5.3-1.4 6.9Z';
const BLOSSOM: LucideIconNode[] = [
  ...[0, 72, 144, 216, 288].map((angle): LucideIconNode => ['path', { d: PETAL, transform: `rotate(${angle} 12 12)`, key: `petal-${angle}` }]),
  ['circle', { cx: '12', cy: '12', r: '1', key: 'centre' }],
];
export const Blossom = createLucideIcon('blossom', BLOSSOM);
